# Pull tomcat :8-jre8 image from dockerhub 
From tomcat:8-jre8

# Maintainer
MAINTAINER Abdou Karim, nofatard@gmail.com 

# copy war file on to container 
COPY ./webapp/target/webapp.war /usr/local/tomcat/webapps
